/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
**/

var currNumber = 1;
var prevNumber = 1;
var sum = 0;

while(currNumber <= 4000000) {
    var tempSum;
    tempSum = currNumber + prevNumber;
    if(tempSum % 2 === 0) {
        sum += tempSum;
    }
    prevNumber = currNumber;
    currNumber = tempSum;
    
}

console.log("Sum is " + sum);